import type { NFT } from "./types"

export const nfts: NFT[] = [
  {
    id: "1",
    name: "Cosmic Voyager #001",
    description: "A journey through the cosmos, captured in digital art.",
    image: "/images/nft1.png",
    price: 1.25,
    creator: "CryptoArtist",
    owner: "Collector123",
    category: "art",
  },
  {
    id: "2",
    name: "Digital Dreamscape #42",
    description: "Explore the boundaries of imagination in this digital dreamscape.",
    image: "/images/nft2.png",
    price: 0.75,
    creator: "DreamWeaver",
    owner: "NFTWhale",
    lastSale: 0.65,
    category: "art",
  },
  {
    id: "3",
    name: "Pixel Punk #789",
    description: "A unique pixel art character with attitude.",
    image: "/images/nft3.png",
    price: 2.5,
    creator: "PixelMaster",
    owner: "Collector123",
    lastSale: 2.2,
    category: "collectibles",
  },
  {
    id: "4",
    name: "Abstract Emotions #12",
    description: "Feelings translated into abstract digital art.",
    image: "/images/nft4.png",
    price: 1.8,
    creator: "EmotionalArtist",
    owner: "ArtLover",
    category: "art",
  },
  {
    id: "5",
    name: "Crypto Kitty #256",
    description: "An adorable digital cat with unique traits.",
    image: "/images/nft5.png",
    price: 0.5,
    creator: "KittyCreator",
    owner: "CatFancier",
    lastSale: 0.45,
    category: "collectibles",
  },
  {
    id: "6",
    name: "Virtual Land Plot #A12",
    description: "Prime virtual real estate in the metaverse.",
    image: "/images/nft6.png",
    price: 5.0,
    creator: "LandDeveloper",
    owner: "MetaverseInvestor",
    category: "virtual worlds",
  },
  {
    id: "7",
    name: "Digital Soundwave #003",
    description: "A visual representation of a unique audio track.",
    image: "/images/nft7.png",
    price: 0.9,
    creator: "AudioVisualizer",
    owner: "MusicLover",
    category: "music",
  },
  {
    id: "8",
    name: "Crypto Punk #1337",
    description: "One of the original crypto punks with rare attributes.",
    image: "/images/nft8.png",
    price: 15.0,
    creator: "PunkCreator",
    owner: "RarityCollector",
    lastSale: 12.5,
    category: "collectibles",
  },
]

export const userNfts: NFT[] = [
  {
    id: "101",
    name: "My First NFT #1",
    description: "The first NFT in my collection.",
    image: "/images/nft1.png",
    price: 1.0,
    creator: "You",
    owner: "You",
    category: "art",
  },
  {
    id: "102",
    name: "Digital Masterpiece #7",
    description: "A true masterpiece in your collection.",
    image: "/images/nft2.png",
    price: 2.5,
    creator: "FamousArtist",
    owner: "You",
    lastSale: 2.3,
    category: "art",
  },
  {
    id: "103",
    name: "Rare Collectible #42",
    description: "A rare collectible item with unique properties.",
    image: "/images/nft3.png",
    price: 3.2,
    creator: "CollectibleCreator",
    owner: "You",
    category: "collectibles",
  },
  {
    id: "104",
    name: "Virtual Pet #789",
    description: "Your very own virtual pet on the blockchain.",
    image: "/images/nft4.png",
    price: 0.8,
    creator: "PetCreator",
    owner: "You",
    lastSale: 0.75,
    category: "collectibles",
  },
  {
    id: "105",
    name: "Music Token #12",
    description: "Ownership of this exclusive music track.",
    image: "/images/nft5.png",
    price: 1.5,
    creator: "MusicArtist",
    owner: "You",
    category: "music",
  },
]
